-------------------------------------------------------------------------------
Test set: PersonTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.335 s <<< FAILURE! - in PersonTest
deletePersonTest(PersonTest)  Time elapsed: 0.032 s  <<< ERROR!
com.github.kevinsawicki.http.HttpRequest$HttpRequestException: java.net.ConnectException: В соединении отказано (Connection refused)
	at PersonTest.deletePersonTest(PersonTest.java:61)
Caused by: java.net.ConnectException: В соединении отказано (Connection refused)
	at PersonTest.deletePersonTest(PersonTest.java:61)

updatePersonTest(PersonTest)  Time elapsed: 0.24 s  <<< ERROR!
com.github.kevinsawicki.http.HttpRequest$HttpRequestException: java.net.ConnectException: В соединении отказано (Connection refused)
	at PersonTest.updatePersonTest(PersonTest.java:52)
Caused by: java.net.ConnectException: В соединении отказано (Connection refused)
	at PersonTest.updatePersonTest(PersonTest.java:52)

addPersonTest(PersonTest)  Time elapsed: 0.002 s  <<< ERROR!
com.github.kevinsawicki.http.HttpRequest$HttpRequestException: java.net.ConnectException: В соединении отказано (Connection refused)
	at PersonTest.addPersonTest(PersonTest.java:17)
Caused by: java.net.ConnectException: В соединении отказано (Connection refused)
	at PersonTest.addPersonTest(PersonTest.java:17)

